[package]
name = "rm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
rand = "0.8.5"
anyhow = "1.0.68"
promptly = "0.3.1"
