[package]
name = "md5sum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
md5 = "0.7.0"
anyhow = "1.0.62"
rand = "0.8.5"
