[package]
name = "cat"
version = "0.1.0"
authors = ["Sarah <rasdrive4165@protonmail.com>"]
edition = "2018"

[dependencies]
crossterm = "0.21.0"
clap = { version = "3.1.18", features = ["derive"] }

[dependencies.tui]
version = "0.16.0"
default-features = false
features = ["crossterm"]
